# Task 1: Web Scraping

## Objective

The objective of this task is to extract structured data from a public website using Python and BeautifulSoup, convert the scraped information into a Pandas DataFrame, and create a custom dataset for further analysis.

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [14]:
url = "https://books.toscrape.com/"

response = requests.get(url, timeout=10)

print("Status Code:", response.status_code)

Status Code: 200

In [15]:
print("kernel is working")

kernel is working

In [16]:
url = "https://books.toscrape.com/"

response = requests.get(url, timeout=5)

print("Status Code:", response.status_code)

Status Code: 200

In [17]:
soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print("Number of books:", len(books))

Number of books: 20

In [18]:
data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").get_text(strip=True)
    rating = book.find("p", class_="star-rating")["class"][1]
    availability = book.find("p", class_="instock availability").get_text(" ", strip=True)

    data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    })

df = pd.DataFrame(data)

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [19]:
df["Price"] = (
    df["Price"]
    .str.replace("Â", "", regex=False)
    .str.replace("£", "", regex=False)
    .astype(float)
)

df.head()

                                   Title  Price Rating Availability
0                   A Light in the Attic  51.77  Three     In stock
1                     Tipping the Velvet  53.74    One     In stock
2                             Soumission  50.10    One     In stock
3                          Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  54.23   Five     In stock

In [20]:
df.head()

                                   Title  Price Rating Availability
0                   A Light in the Attic  51.77  Three     In stock
1                     Tipping the Velvet  53.74    One     In stock
2                             Soumission  50.10    One     In stock
3                          Sharp Objects  47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  54.23   Five     In stock

In [21]:
df.to_csv("scraped_books_dataset.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [22]:
print("Dataset Shape:", df.shape)
print("\nDataset Columns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Shape: (20, 4)

Dataset Columns:
['Title', 'Price', 'Rating', 'Availability']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     str
 1   Price         20 non-null     float64
 2   Rating        20 non-null     str
 3   Availability  20 non-null     str
dtypes: float64(1), str(3)
memory usage: 772.0 bytes

## Findings

- Data was successfully scraped from a public website using Python.
- A total of 20 book records were collected from the webpage.
- The dataset contains four main attributes: Title, Price, Rating, and Availability.
- The scraped data was converted into a Pandas DataFrame.
- The cleaned dataset was saved as a CSV file for further analysis.

## Conclusion

This task demonstrated how web scraping can be used to collect structured information from a public webpage. BeautifulSoup was used to extract the required information, Pandas was used to organize the data, and the final dataset was saved in CSV format for further analysis.